apiVersion: 1

providers:
  - name: 'Default Alert Rules'
    type: file
    disableDeletion: false
    editable: true
    allowUiUpdates: true
    options:
      path: /etc/grafana/provisioning/alerting/alerting.yml
